# Test the root endpoint

###Test fetching all users
GET http://localhost:4000/users

###Test creating a new user
POST http://localhost:4000/users
Content-Type: application/json

{
  "name": "Naomi Naa",
  "email": "naaomoinn@example.com",
  "age": 24
}

###Test fetching a user by ID
GET http://localhost:4000/users/67deefba2ea312440c46d748

### Test updating a user
PUT http://localhost:4000/users/67df04702160326bfcb43a0a
Content-Type: application/json

{
  "name": "Franca Nan",
  "email": "francenan@gmail.com",
  "age": 43
}


### Test deleting a user
DELETE http://localhost:4000/users/67df04702160326bfcb43a0a

###text admin route
//text our admin page
### Test admin route
// Test our admin page
GET http://localhost:4000/admin

### Create a new admin
POST http://localhost:4000/admin
Content-Type: application/json

{
  "name": "Isaac Torsu",
  "employeeId": "ruco002"
}