# Test the root endpoint

###Test fetching all users
GET http://localhost:4000/users

###Test creating a new user
POST http://localhost:4000/users
Content-Type: application/json

{
  "name": "Prince Nant",
  "email": "princenant@example.com",
  "age": 19
}

###Test fetching a user by ID
GET http://localhost:4000/users/67e1d838ae547f10fb7a2af8

### Test updating a user
PUT http://localhost:4000/users/67e1d838ae547f10fb7a2af8
Content-Type: application/json

{
  "name": "Prince Nanty",
  "email": "francenan@gmail.com",
  "age": 34
}


### Test deleting a user
DELETE http://localhost:4000/users/67e1d8b2ae547f10fb7a2aff

###text admin route
//text our admin page
### Test admin route
// Test our admin page
GET http://localhost:4000/admin

### Create a new admin
POST http://localhost:4000/admin
Content-Type: application/json

{
  "name": "Emmanuella Dan",
  "employeeId": "ruco005"
}


###
PUT http://localhost:4000/admin

###
DELETE http://localhost:4000/admin